version: '3'

services:
# ----- Development Build Script -----
# This is the development build script for the API 
# Note, this script will not run migrations automatically
# ------ ------------------------- ----
  api: 
    build: ./Docker/
    command: python3 -m manage runserver 0.0.0.0:8080
    volumes: 
      - .:/backend
    ports:
      - 8080:8080
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
volumes:
  postgres_data:
